// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config = {
  API: {
    GraphQL: {
      endpoint:
        'https://nukrqo3vtjchtpc353ia2zonbm.appsync-api.us-east-1.amazonaws.com/graphql',
      region: 'us-east-1',
      defaultAuthMode: 'apiKey',
      apiKey: 'da2-zvsiimm5sndelddl2mc6wh4a7e',
    },
  },
};
 

export default config;
